name: Build Windows App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows
      - name: Upload Portable windows app
        uses: actions/upload-artifact@v4
        with:
          name: bill-manager-windows
